### ISSUE TITLE
Blender Avatars cannot teleport

### ISSUE THREAD

**Issue by Menithal** [highfidelity/hifi#10566]
I am getting reports, and I can confirm that blender avatars are unable to teleport using the teleport.js . 

So avatars using the bone structure defined in the Blender Compendium Thread are not able to teleport using the controllers

**Comment by nconn** [comment]
I can confirm, having encountered this with an avatar created in Blender just today. (avatar in question attached) 
[Plumbot_09.zip](https://github.com/highfidelity/hifi/files/1036322/Plumbot_09.zip)

**Comment by hyperlogic** [comment]
@nconn can you include the full url to the fbx file?  The fst file by itself doesn't help me track down the problem.

**Comment by nconn** [comment]
@hyperlogic Sure, that particular revision no longer exists, but the updated one still has this problem. The new fst can be found here, http://west.nexusheavy.com/athauxan/PlumbotUpload/Plumbot_20.fst and the all of the assets for it can be found in this directory. http://west.nexusheavy.com/athauxan/PlumbotUpload/Plumbot_20/

**Comment by hyperlogic** [comment]
ok thanks will take a look

**Comment by hyperlogic** [comment]
I think this is because this skeleton is missing the following joints:

* RightToeBase
* RightToe_End
* LeftToeBase
* LeftToe_End

teleport.js uses this to measure a good position to place the avatar such that his feet reach the ground.  It's still a bug, but as a workaround if you add these bones to your model you should be able to teleport.

**Comment by hyperlogic** [comment]
Please, try PR #10613 to see if it fixes this issue.
