### ISSUE TITLE
Adding actions in VrMenu.cpp doesn't work - segfault on startup

### ISSUE THREAD

**Issue by ChristophHaag** [highfidelity/hifi#8305]
On Archlinux with qt 5.7.0.

gdb backtrace: https://gist.github.com/ChristophHaag/9bbb442395825fe90dae7dd20ef9a889

It's caused by this call not working: https://github.com/highfidelity/hifi/blob/592a50356bf598a4ca49d45c0c30525477831c6d/libraries/ui/src/VrMenu.cpp#L172-L174
I tried debugging a bit but I have no idea how to debug this generic indirection mess. But `invokeResult` is false, so something is going wrong.

A workaround is skipping the actions that fail to be added: https://github.com/ChristophHaag/hifi/commit/ac207dd431ff956863f5c2ea9de9153f9b756d8d
Then interface starts and is sorta usable.
But it skips _a lot_ of actions, so there is probably some general problem.

Happens on RELEASE-5181 and master (currently 89d9affb417de363f718109fe8f3af6721b28a33).

**Comment by ZappoMan** [comment]
We don't currently support Qt 5.7. We currently only officially supporting Qt 5.5.x. We will be upgrading to Qt 5.6 soon. We are not currently planning on support Qt 5.7. Qt 5.6 is Qt's Long Term Support release, and so we will likely remain with Qt 5.6 compatibility for the foreseeable future.

**Comment by ChristophHaag** [comment]
So this is probably because the newer Qt version changed something? Hm.

I will probably try again with one of the precompiled Qt builds they provide on their website then. This is going to be a bit of a headache for modern linux distributions if they want to provide a package for hifi.

Thanks for the info.

**Comment by jherico** [comment]
@ChristophHaag The update to Qt 5.6 required some changes because of internal changes in Qt relating to menus.  In particular they renamed `QQuickMenuItem` to `QQuickMenuItem1`.  Normally applications don't need to care about this sort of thing because they don't reference the QML C++ types.  We're doing some interaction with the QML C++ menu types in order to keep our widget based menu and the VR menu in sync.  You can see the changes in [this commit](https://github.com/highfidelity/hifi/pull/8405/commits/cef0218b20176e069e6b4318304b0749f8606a3a).

You _might_ be able to get a build working by using #8405 as a starting point, but as @ZappoMan says, 5.5.1 is the only officially supported Qt version at the moment, so you're kind of on your own if 5.7 (and currently 5.6) don't work out of the box.  Sorry, and good luck.

**Comment by ChristophHaag** [comment]
Thanks for the explanation.

I tried a bit with downloading a qt 5.5 build from the qt download archive but didn't really succeed in making cmake use only that qt version, not with `-DQt5_DIR` or `-DQT_CMAKE_PREFIX_PATH` etc...

If at least the cmake build system could made to be work with qt builds in nonstandard directories I'd be happy.

**Comment by ChristophHaag** [comment]
Works with the qt 5.6 installer from the qt website and `QT_CMAKE_PREFIX_PATH=/wherever/Qt5.6.2/5.6/gcc_64/lib/cmake cmake`
