### ISSUE TITLE
Menus added to VrMenu can't later be removed

### ISSUE THREAD

**Issue by humbletim** [highfidelity/hifi#8814]
Looks like `Menu.removeMenu` is only affecting the main dropdowns and not the VrMenu popup.

`Menu.removeMenuItem` seems to work fine for removing items _within_ menus -- it's just the menus/submenus that seem to become permanent.

Here is a short snippet to demostrate:

``` javascript
for(var i=0; i < 3; i++) { Menu.addMenu('Test'); Menu.removeMenu('Test'); }
```

After running that would expect no traces of "Test" to remain, but:

![menutest](https://cloud.githubusercontent.com/assets/94753/19401328/b6fdc6aa-9228-11e6-924c-913a37c85535.png)

**Comment by AndrewMeadows** [comment]
Maybe someone fixed this?  I can't reproduce -- the **Test** menu is properly added and deleted as expected.

**Comment by AndrewMeadows** [comment]
Sorry, my mistake.  this is still a problem.

**Comment by druiz17** [comment]
I'm currently working on this.

**Comment by howard-stearns** [comment]
Hey, there may (or may not) be some duplication between the following. Since various people have different parts of this, I want to make everyone aware:
https://github.com/highfidelity/hifi/issues/8814
https://highfidelity.fogbugz.com/f/cases/1953/Menus-added-to-VrMenu-can-t-later-be-removed
https://highfidelity.fogbugz.com/f/cases/2263/Audio-menu-listing-devices-repeatedly
https://highfidelity.fogbugz.com/f/cases/2297/Duplicate-Audio-Devices-menu
