### ISSUE TITLE
Script.include() ignoring previously included: Breaks library use in multiple entities.

### ISSUE THREAD

**Issue by Menithal** [highfidelity/hifi#9012]
This breaks usage of using external library / or utility scripts within entities, as set variables never be set for the instance.

New entities using the same script ignore the entire Script.include line, causing issues as references created in the library script are never defined every subsequent time the script is run. If you have multiple entities running the same script that has the Script.include, basically only one of the entities will ever run without errors.

Reloading the script also causes this not to be re-run. Current work around is to use
> Script.include("script?" + Math.random());

This doesnt take advantage of the caching if we have to randomize each instance, and it also does not fix the issue if multiple scripts are running the same script.

This is especially vital for having external framework libraries, such as the one [I am working on.](https://github.com/Menithal/hifi-js-wrap)

**Comment by humbletim** [comment]
This is also a problem when exporting APIs for Entity scripts using globals, but for different reasons.

In the case of globals it doesn't matter whether subsequent includes get re-included -- only that the first one completes evaluation before any related Entity script is allowed to proceed past its `Script.include` line.

But what happens right now in a stampede is that the first Entity causes the previous flag to get set and waits accordingly for the include -- but all immediately-next Entities see that flag and proceed right into execution (long before the previous include is even fetched, let alone evaluated).

**Comment by sethalves** [comment]
Is this due to
```javascript
void ScriptEngine::include(const QStringList& includeFiles, QScriptValue callback) {
    ...
    if (!_includedURLs.contains(thisURL)) {
        ...
    } else {
        qCDebug(scriptengine) << "Script.include() ignoring previously included url:" << thisURL;
    }
}
```
?

**Comment by sethalves** [comment]
I think that https://github.com/highfidelity/hifi/pull/9051 will address @humbletim's complaint but not @Menithal's.  Does this seem true?  How would we test this?

**Comment by humbletim** [comment]
I think three scripts are needed for testing either case -- eg: `client.js -> entity.js -> include.js`
...can try to find the local starting point I had going the other day.

@Menithal would the de facto "require/module.exports" pattern work for your case? eg: something like this:
```javascript
// framework.js include
module.exports = { Entity: Entity, Overlay: Overlay };
function Entity() { }
function Overlay() { }
```
```javascript
// Entity script
(function() {
  var api = Script.require('framework.js'),
        Entity = api.Entity;
  var e = new Entity();
  [...]
})
```
??

@sethalves with #9051 I think there's a straightforward way now to emulate the above module pattern -- basically, using a new `QScriptValue Script::require(QString)` method that "pushes" an empty `module.exports` global property, delegates to `Script::include`, "pops" `module.exports` off and memoizes the `.exports` part while returning it.  Probably a little more complicated than that, but if you think it might fly I'd be willing to take a stab at coding it up.

**Comment by Menithal** [comment]
@sethalves  basically I'd like to have something akin to what @humbletim mentioned there.

**Comment by ZappoMan** [comment]
@Menithal @humbletim - Let me first say... thank you very much for raising this issue. The core dev team here at high fidelity is also very interested in addressing this issue of script code reuse, we've been doing some (and will continue to do some) hard thinking about this topic. Unfortunately, we have not come up with a good answer yet... and each direction we turn has different trade offs.

If you take a quick spin around google, and search for how other languages and systems  (php, ruby, es6, node, etc) use these patterns you will quickly see that `include`, `require`, `import`, `once`, `inline` and the like are all used differently and mean different things in different systems. Admittedly, we might have chosen the less obvious option for our semantics of `include` but, it's clear that there are lots of other teams that have similarly heated debates about the possible semantics of each of these methods.

Here's what we are sure we want to solve (somehow) ---

**re-evaluation vs single-evaluation of the code** - currently our `Script.include` only evaluates the code once. We agree that there are uses where you sometimes want to re-evaluate each time. But it's also clear that many other language/library teams agree that you often don't want to constantly re-evaluate the code... we weren't alone in that thought.

**synchronous vs asynchronous loading** - `Script.include()` should be synchronous when you use a single file, and is always synchronous when you give it a list of files. We do think there's a race condition bug in the synchronous version that we're trying to fix. Whether or not other possible approaches need both synchronous and asynchronous loading is obviously a source of great debate in the community at large. We suspect this vector needs to be available for other "reuse" methods as well.

**evaluation scope/context** - This is another issue of great debate in the community at large... where the code is evaluated will have implications for any language, since all these languages support global and local (scoped) variables and function they all deal with this notion of context differently... the choices we make in any changes or additions will be impacted by this issue. When we first wrote the rules for `Script.include()` we chose single evaluation because it essentially eliminates the issue of context... because by definition the context is where you first do the include. That is admittedly part of what is biting us now.

**failure vs warn and continue** - Different reuse paradigms also introduce different rules for handling exceptions. This is something we are evaluating further as well.

**dynamic loading vs static defined** - Different reuse paradigms support dynamic, runtime paths that include different modules... while others require you to state these dependencies up front. I think we're going to need our system to be dynamic in nature (as it is now), but for completeness, I'm mentioning this here, since it is a feature vector in other systems.

Next steps... @sethalves and @howard-stearns and I are proactively working through some of these issues, and we hope to make some baby steps in fixing some of these issues in the short term. In the medium term, we will come up with a proposal for how we would like to add different methods for code reuse to the system. Please stay tuned.

**Comment by Polyrhythm** [comment]
I think commonJS require syntax, as used by default by NodeJS, is a pretty safe pattern to emulate, and would allow for maximum flexibility with importing external libraries for using by scripters. If i want to use an NPM module, I'll l'll likely need to shim support for `require` expressions so that the code I import can be used. Seems like a pretty safe option.

ES6 import statements are simply syntactic sugar over require anyway, and are meant to coexist peacefully with them.

**Comment by Menithal** [comment]
@ZappoMan  I pretty much am the same opion as with @Polyrhythm  regarding the subject, better keep consistancy to other JS-based scripting languages for easier adaptation by other content creators.

**Comment by humbletim** [comment]
... I've been using modules with High Fidelity scripting for over a year now; even ported [SystemJS](https://github.com/systemjs/systemjs) over.

I mention that because I don't really need another module system...

What I'd like to see here (which I believe also solves in principle what other are asking for) is a *shared* module approach that is capable of addressing specific collaboration scenarios, such as the following:

Non-expert scripters are attempting to create complex things on the High Fidelity platform -- and more often than not, having to *abandon* their pursuits for stated reasons of perceiving unworkable dead ends at the scripting level.

Meanwhile, a handful of expert scripters seem ready, willing and able to offer assistance to those getting stuck... except wait, they cannot realistically do so -- because the system makes collaboration at that level nearly impossible to approach *efficiently* right now (at least in terms of built-in features only).

... what seems needed then is a reasonable, consistent, and scoped way for scripters who would assist others... to be able to assist others... by way of helper modules they already think to create.

This is not a new problem.  And to me the known variables suggest [`require / module.exports`](https://gist.github.com/humbletim/807d041d689df196e8b71a485ebf1d82#file-require-module-exports-md) would not be a terrible way to go for now (link contains an outline of specific reasons to think so).

**Comment by Menithal** [comment]
Alternative has been available via `Script.require` / `module.exports` for a while now, closing this issue.
