### ISSUE TITLE
Tablet Pop-up relocation:  Developer > Render >LOD Tools

### ISSUE THREAD

**Issue by cozza13** [highfidelity/hifi#9771]

**Comment by vladest** [comment]
starting this

**Comment by vladest** [comment]
PR: https://github.com/highfidelity/hifi/pull/9866

**Comment by ctrlaltdavid** [comment]
This has been merged into tablet-ui; is there any further work required on it?

**Comment by vladest** [comment]
nope, as far as I know

**Comment by ctrlaltdavid** [comment]
Issues:
- Red text can be too long for tablet screen width.
- If Settings > General > HMD Tablet Becomes Toolbar is set, the dialog is not displayed in the HMD (the desktop dialog is displayed on the desktop).
- Checkbox should be to left of text, like it is in Settings > General and similar dialog.
- Button should be normal button size.

**Comment by vladest** [comment]
Please give me example of HMD. In general, what the difference between Desktop and HMD windows?

**Comment by ctrlaltdavid** [comment]
Dialogs should be able to be displayed in two manners: window and tablet. Both implemented in QML. Either window or tablet manner can be displayed when in desktop mode. and either window or tablet can also be displayed in HMD mode. Two settings control which type is displayed in which mode: Settings > General > Desktop Tablet Becomes Toolbar and ... > HMD Tablet Becomes Toolbar.

The LOD Tools dialog currently uses C++ to display "desktop window" which means it doesn't display in the HMD when you've selected HMD Tablet Becomes Toolbar. Instead. it displays on the PC's display.

The LOD Tools dialog's C++ - LodToolsDialog.h, .cpp - should be able to be deleted and replaced with QML so that like other dialogs there's a "desktop" (i.e., window) version and a tablet version. The common QML code for the dialog content should be able to be factored out: e.g., the avatar attachments dialogs has AttachmentsDialog.qml and TabletAttachmentsDialog.qml, both of which use AttachmentsContent.qml.

**Comment by vladest** [comment]
ok, thanks for clarification. I did not know that Desktop C++ dialogs should be refactored to QML as well. Will start on that after finishing current task

**Comment by vladest** [comment]
starting on this
